version: '3.5'
services:
  postgres:
    image: habits/postgres
    hostname: postgres
    networks:
      - lan
    ports:
      - 5432:5432
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgress
      - PGDATABASE=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    build:
      context: ./postgres
  tracker-service:
    image: habits/tracker-service
    hostname: tracker-service
    depends_on:
      - postgres
    networks:
      - lan
    build:
      context: ./tracker-service
  api-gateway:
    image: habits/api-gateway
    hostname: api-gateway
    networks:
      - lan
    build:
      context: ./api-gateway
  frontend:
    image: habits/frontend
    hostname: frontend
    networks:
      - lan
    ports:
      - 80:80
    build:
      context: ./frontend
networks:
  lan:
    driver: bridge
volumes:
  pgdata:
