version: '3.5'
services:
  postgres:
    image: postgres:latest
    hostname: postgres
    networks:
      - lan
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  tracker-service:
    image: habits/tracker-service
    hostname: tracker-service
    networks:
      - lan
    build:
      context: ./tracker-service
  api-gateway:
    image: habits/api-gateway
    hostname: api-gateway
    networks:
      - lan
    ports:
      - 8080:8080
    build:
      context: ./api-gateway
networks:
  lan:
    driver: bridge
volumes:
  pgdata:
