package dev.tadite.habits.projects.db.migration;

import dev.tadite.habits.projects.db.MigrationUtils;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

public class V3__Tasks extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        new JdbcTemplate(new SingleConnectionDataSource(context.getConnection(), true))
                .execute("create table " + MigrationUtils.getSchema(context) + ".task (\n" +
                        "    id integer generated by default as identity not null primary key,\n" +
                        "    project_id integer not null,\n" +
                        "    parent_id integer,\n" +
                        "    created_at timestamp not null,\n" +
                        "    name varchar(200) not null,\n" +
                        "    description varchar(5000),\n" +
                        "    foreign key (project_id) references project(id),\n" +
                        "    foreign key (parent_id) references task(id)\n" +
                        ");");
    }
}
