package dev.tadite.habits.tracker.db.migration;

import dev.tadite.habits.tracker.db.MigrationUtils;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

public class V2__Records extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        new JdbcTemplate(new SingleConnectionDataSource(context.getConnection(), true))
                .execute("create table " + MigrationUtils.getSchema(context) + ".record (\n" +
                        "    id integer generated by default as identity not null primary key,\n" +
                        "    project_id varchar(50) not null,\n" +
                        "    start_time timestamp,\n" +
                        "    end_time timestamp,\n" +
                        "    description varchar(5000)\n" +
                        ");");
    }
}
