zuul.routes:
  tracker-service:
    path:
      /tracker/**
    serviceId:
      tracker-service
  project-service:
    path:
      /projects/**
    serviceId:
      project-service
  history-service:
    path:
      /history/**
    serviceId:
      customer-history-service

eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka