spring:
  data:
    mongodb.uri: mongodb://mongo:27017/history
    mongo.repositories.enabled: true
  kafka:
    bootstrap-servers: kafka:9093
    consumer:
      group-id: customer-history-1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: 'dev.tadite.kafka.events'

eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka