package dev.tadite.habits.history.db.migration;

import dev.tadite.habits.history.db.MigrationUtils;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

public class V2__Projects extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        new JdbcTemplate(new SingleConnectionDataSource(context.getConnection(), true))
                .execute("create table "+ MigrationUtils.getSchema(context) +".project (\n" +
                        "    id integer generated by default as identity not null primary key,\n" +
                        "    created_at timestamp not null,\n" +
                        "    name varchar(200) not null,\n" +
                        "    description varchar(5000)\n"+
                        ");");
    }

}
